### ISSUE TITLE
Blitz and Java 8

### ISSUE THREAD

**Issue by nkabir** [dancres/blitzjavaspaces#3]
Apologies but I haven't been able to find any references to Java 8. Does Blitz work on Java 8? Ideally, I'd like to deploy Blitz on Java 8 via Docker. I'm also willing to submit patches if you need a hand.

**Comment by dancres** [comment]
I've not done any specific verification work against Java 8. I'm not aware of any reports that it doesn't work and there's nothing changed in Java that I'd expect to break Blitz. Famous last words of course.

You'd be doing me a favour if you just tried it and sent me any exceptions or whatever that you encounter.

**Comment by dancres** [comment]
A limited test today suggests Blitz will run just fine under Java 8.

**Comment by nkabir** [comment]
Thank you! I will post any problems on this issue.
