### ISSUE TITLE
Update Getting Started documentation.

### ISSUE THREAD

**Issue by baardl** [dancres/blitzjavaspaces#6]
Hi Dan.

Please, can we make some Hello World example, and document this in an easy to reach place?

Thanks.
Bård

**Comment by dancres** [comment]
It's all in the docs part of the source distribution: https://github.com/dancres/blitzjavaspaces/blob/master/docs/hello_example.html or online here: http://dancres.org/bjspj/docs/docs/hello_example.html - not what you want? Let me know!
